# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb425d5f4995e0f5838fdc68b3e0085157c01e1eadc30c036cf88001fffdaba76252279242af0a86cb62616115c6fb336e6fb95f854db310eac7794a3ff21036

test:
  secret_key_base: 0bbb6e159b3c9fc585090474c7820d7d53ae12d461fc41f71609ac4e4265b93390533c26e18f2e68498282cbdc9808ae643f0ed7e763efda91751b267404754d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
